[package]
name = "atri_botctl"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
dashmap = "5"
atri_plugin = "0.5.1"

[profile.release]
lto = true
strip = true
codegen-units = 1